import { describe, expect, it } from "vitest";
import { stripSecrets } from "@/lib/strip-baked-env";

const source = [
  'export const production = {"ANTHROPIC_API_KEY":"secret-a","NEXT_PUBLIC_SITE_NAME":"canopus"};',
  'export const development = {"DATABASE_URL":"secret-b","NEXT_PUBLIC_SITE_NAME":"canopus"};',
  "export const test = {};",
  "",
].join("\n");

describe("stripSecrets", () => {
  it("keeps NEXT_PUBLIC_ keys and drops everything else in every mode", () => {
    const { output } = stripSecrets(source);

    expect(output).toBe(
      [
        'export const production = {"NEXT_PUBLIC_SITE_NAME":"canopus"};',
        'export const development = {"NEXT_PUBLIC_SITE_NAME":"canopus"};',
        "export const test = {};",
        "",
      ].join("\n"),
    );
    expect(output).not.toContain("secret-a");
    expect(output).not.toContain("secret-b");
  });

  it("reports the dropped key names, qualified by mode", () => {
    const { dropped } = stripSecrets(source);

    expect(dropped).toEqual([
      "production.ANTHROPIC_API_KEY",
      "development.DATABASE_URL",
    ]);
  });

  it("handles a mode with an empty object", () => {
    const { output, dropped } = stripSecrets("export const test = {};\n");

    expect(output).toBe("export const test = {};\n");
    expect(dropped).toEqual([]);
  });

  it("leaves unrelated lines untouched", () => {
    const other = [
      "// generated by opennextjs-cloudflare",
      'export const production = {"RESEND_API_KEY":"secret-c"};',
      'const notAnExport = {"RESEND_API_KEY":"secret-d"};',
      "export default production;",
      "",
    ].join("\n");

    const { output, dropped } = stripSecrets(other);

    expect(output).toBe(
      [
        "// generated by opennextjs-cloudflare",
        "export const production = {};",
        'const notAnExport = {"RESEND_API_KEY":"secret-d"};',
        "export default production;",
        "",
      ].join("\n"),
    );
    expect(dropped).toEqual(["production.RESEND_API_KEY"]);
  });
});
